### ISSUE TITLE
Check that npm version is 7+

### ISSUE THREAD

**Issue by jaredgalanis** [ember-learn/tool-new-release#44]
When releasing Ember 5.1 using this tool I ran into an issue where because I had npm 6.x installed the tool could not build the guides as it changed the lockfile version from 2 to 1.

We should consider checking and enforcing an npm version that is 7+. 

https://docs.npmjs.com/cli/v9/configuring-npm/package-lock-json#lockfileversion

**Comment by locks** [comment]
I don't think this is the way to go, for a couple of reasons:
1) This specific case is a symptom of the required node version for `guides-source` being ["12.* || 14.* || >= 16"](https://github.com/ember-learn/guides-source/blob/master/package.json#L117). Bumping it to `16` brings npm to `8` which avoids the problem
2) If we're not going to use a package manager, I think we should do a more generic step of checking `engines` in `package.json` instead of hardcoding a check like this. As we're about to see with the Node version check, hardcoded values are bound to get outdated and drift.

**Comment by jaredgalanis** [comment]
> I don't think this is the way to go, for a couple of reasons:
> 
> 1. This specific case is a symptom of the required node version for `guides-source` being ["12.* || 14.* || >= 16"](https://github.com/ember-learn/guides-source/blob/master/package.json#L117). Bumping it to `16` brings npm to `8` which avoids the problem
> 2. If we're not going to use a package manager, I think we should do a more generic step of checking `engines` in `package.json` instead of hardcoding a check like this. As we're about to see with the Node version check, hardcoded values are bound to get outdated and drift.

Yeah I agree that bumping to require 16 would resolve the issue for almost all people. For me, I've got 16 installed and I think I might have still hit this. 

I'm happy enough to close this if you think it's not the preferred solution. 

OR, the title of this issue doesn't have to prescribe the solution. We could generalize or adapt it to your suggestion of checking engines.
